### ISSUE TITLE
Error after upgrading to 0.1.7

### ISSUE THREAD

**Issue by wachunga** [voodootikigod/postmark.js#12]
Since upgrading to 0.1.7, I'm now getting errors:

> status=422, message="Received invalid JSON input."

Seems to be a regression of some sort. Downgrading to 0.1.6 for now.

**Comment by sitepodmatt** [comment]
I got the same error with our package dependencies,  was listed as "~0.1.6" hence on latest pull we got 0.17, downgraded to 1.0.6 via pinning the deps, can you please respect semver, changes at this level should not be breaking.
